### ISSUE TITLE
[bug] 쪽지 생성시 101자까지 입력되는 현상

### ISSUE THREAD

**Issue by 2unbini** [Happiggy/Happiggy-bank-iOS#164]
### 기기
iPhone 11

### 내용
![IMG_6508](https://user-images.githubusercontent.com/75126613/163091059-b58576d6-337f-44a4-9499-b0a8320f1900.PNG)

쪽지 생성시 101자까지 입력되는 현상 발생.
쪽지 저장할 때에는 100자로 잘림.

**Comment by skkimeo** [comment]
한글 입력 체계상 어쩔 수 없어서 의도한 현상이 맞습니당! 현재 임시방편으로 100자를 초과하면 오른쪽 아래 글자 수 라벨에서 현재 글자 수가 빨간색으로 표시되도록 변경했습니다~
