### ISSUE TITLE
[bug] 노티피케이션 알림 반복

### ISSUE THREAD

**Issue by 2unbini** [Happiggy/Happiggy-bank-iOS#168]
저금통 개봉 후에도 노티피케이션 알림이 반복됨

**Comment by skkimeo** [comment]
![IMG_1160](https://user-images.githubusercontent.com/81314063/164192718-3c3e2ade-da97-46ff-ae57-8e08b02c1eae.PNG)

이 현상 말하시는 거 맞나유...? 저도 어제 보고 내일 피드백에 써놔야지 했습니당 흑흑

**Comment by 2unbini** [comment]
그거 아니었고 푸시알림이 계속 반복되는거였는데 저건 왜 저럴까요...
